import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

// Initialize the Supabase Admin Client
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
);

export async function POST(req) {
  try {
    const body = await req.json();
    const { firstName, lastName, email, password } = body;

    // Basic validation
    if (!email || !password || !firstName || !lastName) {
      return NextResponse.json(
        { message: "All fields are required" },
        { status: 400 },
      );
    }

    // 1. Create the user in Supabase Auth (This makes them show in the user list)
    const { data: authData, error: authError } =
      await supabaseAdmin.auth.admin.createUser({
        email,
        password,
        email_confirm: true,
        user_metadata: { full_name: `${firstName} ${lastName}` },
      });

    if (authError) {
      return NextResponse.json({ message: authError.message }, { status: 400 });
    }

    const fullName = `${firstName} ${lastName}`;

    // 2. Also insert into your custom 'users' table for profile data
    // Note: Use the ID generated by Supabase Auth to keep them linked
    const { error: insertError } = await supabaseAdmin.from("users").insert([
      {
        id: authData.user.id,
        email: email,
        full_name: fullName,
      },
    ]);

    if (insertError) {
      console.error("Database Insert Error:", insertError.message);
      return NextResponse.json(
        { message: `Database Error: ${insertError.message}` },
        { status: 400 },
      );
    }

    return NextResponse.json(
      { message: "User registered successfully" },
      { status: 201 },
    );
  } catch (error) {
    console.error("Registration error:", error);
    return NextResponse.json(
      { message: "Internal Server Error" },
      { status: 500 },
    );
  }
}
